Reanme ./src/ to ./rubber/ and ./rubber to ./rubber-cli
This allows to execute ./rubber-cli directly from the local
checkout/workspace. The only requirement is to run "python3 setup.py
build" first, to generate verison.py.

Instead of

$ ./rubber
raceback (most recent call last):
  File "./rubber", line 4, in <module>
    import rubber.cmdline
ModuleNotFoundError: No module named 'rubber'

users can now

$ python3 setup.py build

and then run ./rubber-cli directly. Without any installation step.